# Generated by Django 4.2.5 on 2023-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
